---

#update host
- include_tasks: hosts.yml
  when: update_hosts

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: enablerabbitmq-plugin.yml

- include: security.yml

- include_tasks: erlang_cookie.yml
  when: rabbitmq_create_cluster

- include_tasks: config.yml

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"

- include_tasks: cluster.yml
  when: rabbitmq_create_cluster == true
